---
provisioner:
  data_bag_path: test/integration/data_bags
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret

suites:
  - name: default
    attributes:
      users:
        - test1-staging
    run_list:
      - recipe[osl-app::default]
  - name: systemd
    run_list:
      - recipe[osl-app::systemd]
