---
provisioner:
  data_bag_path: test/integration/data_bags
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret

suites:
  - name: default
    attributes:
      users:
        - test1-staging
    run_list:
      - recipe[sudo]
      - recipe[osl-app::default]
  - name: app1
    attributes:
      users:
        - iam
    run_list:
      - recipe[sudo]
      - recipe[user::data_bag]
      - recipe[osl-app::app1]
      - recipe[osl-app::app2]
