---
provisioner:
  data_bag_path: test/integration/data_bags

suites:
  - name: default
    run_list:
      - recipe[osl-app::default]
  - name: users
    run_list:
      - recipe[osl-app::users]
    attributes:
      osl-app:
        users:
          - test1-staging
