AllCops:
  Include:
    - '**/Berksfile'
    - '**/Cheffile'
  Exclude:
    - 'metadata.rb'

Metrics/BlockNesting:
  Max: 4

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false
